 <header>
        <a href="index.php">  <img src="images/logo.jpg" width="100" height="100" alt="logo" class="logo" /></a>
        <!--The menu that links to the other pages-->
        <nav>
            <ul >
                <li class="menu"><a href="index.php" >HOME</a></li>
                <li class="menu"><a href="product.php" >BIKES FOR SALE</a></li>
                <li class="menu"><a href="enquire.php" >ENQUIRY FORM </a></li>
                <li class="menu"><a href="about.php" >ABOUT</a> </li>
                <li class="menu"><a href="manager.php" >MANAGER</a></li>
                <li class="menu"><a href="enhancements.php" >ENHANCEMENTS</a></li>
                <li class="menu"><a href="enhancements2.php" >ENHANCEMENTS 2</a></li>
                <li class="menu"><a href="enhancements3.php" >ENHANCEMENTS 3</a></li>

            </ul>
        </nav>
    </header>